import { Rubik } from 'next/font/google'
import { CommentsProvider } from '@/context/CommentsContext'
import "./globals.css"

const rubik = Rubik({
  subsets: ["latin"],
});


export const metadata = {
  title: "Interactive Comments Section",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={rubik.className}
    >
      <body className="min-h-screen w-screen flex flex-col items-center justify-center bg-bg text-text">
        <CommentsProvider>
          {children}
        </CommentsProvider>
      </body>
    </html>
  );
}
